_: {
  flake.homeModules.kitty = { config, pkgs, lib, ... }:
    let
      kittyDir = "${config.home.homeDirectory}/.config/kitty";
    in
    {
      programs.kitty = {
        enable = true;

        font = {
          name = "Inconsolata";
          size = 14;
          package = pkgs.inconsolata;
        };

        # Full shell integration, home-manager-managed. HM always implies `no-rc`
        # in kitty.conf (so the `shell_integration no-rc` line is expected, not a
        # leftover minimal config) and injects the actual sourcing into
        # programs.zsh.initContent. Relies on programs.zsh.enable (homeModules.zsh).
        shellIntegration.enableZshIntegration = true;

        settings = {
          # Remote control only via a per-pid unix socket (not from programs
          # running inside kitty).
          allow_remote_control = "socket-only";
          listen_on = "unix:/tmp/kitty-{kitty_pid}";

          # macOS keeps the native title bar (traffic lights + drag area);
          # elsewhere the titlebar is hidden.
          hide_window_decorations =
            if pkgs.stdenv.hostPlatform.isDarwin then "no" else "titlebar-only";
          window_padding_width = "16 4 0";

          # Layouts: first entry is the default. tall keeps one full-height main
          # window on the left with the rest stacked on the right.
          enabled_layouts = "tall,*";

          modify_font = "cell_height 120%";
          bold_font = "auto";
          italic_font = "auto";
          bold_italic_font = "auto";

          # URLs stay clickable even with detection off; show + underline targets.
          detect_urls = "no";
          show_hyperlink_targets = "yes";
          underline_hyperlinks = "always";

          scrollback_lines = 50000;
          scrollback_pager_history_size = 0;

          macos_quit_when_last_window_closed = "yes";
          update_check_interval = 0;
        };

        keybindings = {
          # Reload config
          "ctrl+shift+f5" = "load_config_file";
          "f5" = "load_config_file";
          # Dump lines with attributes
          "cmd+shift+d" = "dump_lines_with_attrs";
          # Copy last command output
          "ctrl+shift+a" = "launch --stdin-source=@last_cmd_output --type=background clip-copy";
          # Panes (new "window" in kitty's terms) default to re-entry: honor
          # shell re-entry (docker exec / ssh advertised via
          # k_shell_reentry), falling back to a bare `launch --cwd=current`
          # when no advertisement is present. See shell-reentry.md.
          "ctrl+shift+enter" = "kitten shell_reentry.py window";
          "cmd+enter" = "kitten shell_reentry.py window";

          # Tabs and OS windows default to plain cwd-preserving launches, NOT
          # re-entry -- a fresh local shell in the current dir is the more
          # useful default for "bigger" splits; the ssh/docker session itself
          # is what you'd usually want confined to a pane. Re-entry is still
          # one modifier away (shift added on top).
          "ctrl+shift+t" = "launch --cwd=current --type=tab";
          "cmd+t" = "launch --cwd=current --type=tab";
          "ctrl+shift+n" = "launch --cwd=current --type=os-window";
          "cmd+n" = "launch --cwd=current --type=os-window";

          # Secondary binds: same tab/os-window, but with re-entry.
          "ctrl+shift+alt+t" = "kitten shell_reentry.py tab";
          "cmd+shift+t" = "kitten shell_reentry.py tab";
          "ctrl+shift+alt+n" = "kitten shell_reentry.py os-window";
          "cmd+shift+n" = "kitten shell_reentry.py os-window";
        };

        # `include`/`globinclude` can't be expressed via `settings`; HM appends
        # raw extraConfig last, so these override the settings above. `include`
        # accepts absolute paths; `globinclude` rejects them ("Non-relative
        # patterns are unsupported") and resolves relative to the dir
        # containing this kitty.conf -- i.e. ${kittyDir}.
        extraConfig = ''
          # kitty-scrollback.nvim sidecar (generated by modules/features/nixvim.nix)
          include ${kittyDir}/kitty-scrollback.conf

          # DankMaterialShell live theming, written at runtime into ${kittyDir}.
          # globinclude skips silently when the files are absent (e.g. macOS /
          # DMS not running). Must be relative -- see comment above.
          globinclude dank-theme.conf
          globinclude dank-tabs.conf

          # Local hand-edited overrides (not nix-managed; seeded empty if missing).
          # Included last so it overrides everything above. `.conf` so editors
          # syntax-highlight it as kitty config.
          include ${kittyDir}/kitty.custom.conf
        '';
      };

      # Custom kitten used by the re-entry keybinds, plus its protocol doc.
      xdg.configFile."kitty/shell_reentry.py".source = ./_kitty/shell_reentry.py;
      xdg.configFile."kitty/shell-reentry.md".source = ./_kitty/shell-reentry.md;

      # shell_reentry.py's `launch` call always passes `--cwd=current`
      # (reusing the source window's tracked local cwd) even when it's
      # dispatching a re-entry command like `kitty +kitten ssh host`. The ssh
      # kitten's bootstrap then treats that inherited $PWD as its remote cwd
      # target when ssh.conf's `cwd` is unset, and tries to `cd` into it on
      # the remote host -- which fails (noisily, harmlessly) whenever the
      # local and remote path layouts differ -- a macOS `/Users/...` cwd has
      # no counterpart on a Linux box. Pin `cwd` explicitly so
      # it's always evaluated (and expanded) on the remote side instead.
      xdg.configFile."kitty/ssh.conf".text = ''
        cwd $HOME
      '';

      # Producer half of the re-entry protocol: the host-side script that
      # wrappers (docker run, ssh, nix develop) call to publish a re-entry
      # command. Was stranded in the old homeshick `home/bin/` tree after
      # the consumer kitten migrated here 2026-05-25 -- nothing deployed it.
      # PEP-723 script (`uv run --script` shebang); `.local/bin` is on PATH
      # via homeModules.base-dev's sessionPath.
      home.file.".local/bin/k-shell-helper" = {
        source = ./_kitty/k-shell-helper;
        executable = true;
      };

      # kssh: kitty's ssh kitten wrapped with k-shell-helper re-entry
      # publishing, so new tabs opened while ssh'd in land back on the same
      # host. See _kitty/kssh header for the handle-vs-kitten tradeoff.
      home.file.".local/bin/kssh" = {
        source = ./_kitty/kssh;
        executable = true;
      };

      # Seed an editable, non-nix-managed kitty.custom.conf only if absent, so the
      # include never warns and the file stays outside the nix store (store files
      # are read-only, hence the chmod).
      home.activation.seedKittyCustom = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
        kc="${kittyDir}/kitty.custom.conf"
        if [ ! -e "$kc" ]; then
          run mkdir -p "$(dirname "$kc")"
          run cp ${pkgs.writeText "kitty.custom.conf" "# kitty.custom.conf -- local overrides, edit freely. Not managed by nix.\n"} "$kc"
          run chmod u+w "$kc"
        fi
      '';
    };
}
