_: {
  flake.homeModules.kitty = { config, pkgs, lib, ... }:
    let
      kittyDir = "${config.home.homeDirectory}/.config/kitty";
    in
    {
      programs.kitty = {
        enable = true;

        font = {
          name = "Inconsolata";
          size = 14;
          package = pkgs.inconsolata;
        };

        # Full shell integration, home-manager-managed. HM always implies `no-rc`
        # in kitty.conf (so the `shell_integration no-rc` line is expected, not a
        # leftover minimal config) and injects the actual sourcing into
        # programs.zsh.initContent. Relies on programs.zsh.enable (homeModules.zsh).
        shellIntegration.enableZshIntegration = true;

        settings = {
          # Remote control only via a per-pid unix socket (not from programs
          # running inside kitty).
          allow_remote_control = "socket-only";
          listen_on = "unix:/tmp/kitty-{kitty_pid}";

          hide_window_decorations = "titlebar-only";
          window_padding_width = "16 4 0";

          # Layouts: first entry is the default. tall keeps one full-height main
          # window on the left with the rest stacked on the right.
          enabled_layouts = "tall,*";

          modify_font = "cell_height 120%";
          bold_font = "auto";
          italic_font = "auto";
          bold_italic_font = "auto";

          # URLs stay clickable even with detection off; show + underline targets.
          detect_urls = "no";
          show_hyperlink_targets = "yes";
          underline_hyperlinks = "always";

          scrollback_lines = 50000;
          scrollback_pager_history_size = 0;

          macos_quit_when_last_window_closed = "yes";
          update_check_interval = 0;
        };

        keybindings = {
          # Reload config
          "ctrl+shift+f5" = "load_config_file";
          "f5" = "load_config_file";
          # Dump lines with attributes
          "cmd+shift+d" = "dump_lines_with_attrs";
          # Copy last command output
          "ctrl+shift+a" = "launch --stdin-source=@last_cmd_output --type=background clip-copy";
          # Open windows/tabs in the current dir, honoring shell re-entry
          # (docker exec / ssh advertised via k_shell_reentry). Falls back to a
          # bare `launch --cwd=current` when no advertisement is present. See
          # shell-reentry.md.
          "ctrl+shift+enter" = "kitten shell_reentry.py window";
          "ctrl+shift+n" = "kitten shell_reentry.py os-window";
          "ctrl+shift+t" = "kitten shell_reentry.py tab";
          "cmd+t" = "kitten shell_reentry.py tab";
          "cmd+enter" = "kitten shell_reentry.py window";
          "cmd+n" = "kitten shell_reentry.py os-window";
        };

        # `include`/`globinclude` can't be expressed via `settings`; HM appends
        # raw extraConfig last, so these override the settings above. Absolute
        # paths avoid relative-include ambiguity under the store-symlinked
        # kitty.conf.
        extraConfig = ''
          # kitty-scrollback.nvim sidecar (generated by modules/features/nixvim.nix)
          include ${kittyDir}/kitty-scrollback.conf

          # DankMaterialShell live theming, written at runtime. globinclude skips
          # silently when the files are absent (e.g. macOS / DMS not running).
          globinclude ${kittyDir}/dank-theme.conf
          globinclude ${kittyDir}/dank-tabs.conf

          # Local hand-edited overrides (not nix-managed; seeded empty if missing).
          # Included last so it overrides everything above. `.conf` so editors
          # syntax-highlight it as kitty config.
          include ${kittyDir}/kitty.custom.conf
        '';
      };

      # Custom kitten used by the re-entry keybinds, plus its protocol doc.
      xdg.configFile."kitty/shell_reentry.py".source = ./_kitty/shell_reentry.py;
      xdg.configFile."kitty/shell-reentry.md".source = ./_kitty/shell-reentry.md;

      # Seed an editable, non-nix-managed kitty.custom.conf only if absent, so the
      # include never warns and the file stays outside the nix store (store files
      # are read-only, hence the chmod).
      home.activation.seedKittyCustom = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
        kc="${kittyDir}/kitty.custom.conf"
        if [ ! -e "$kc" ]; then
          run mkdir -p "$(dirname "$kc")"
          run cp ${pkgs.writeText "kitty.custom.conf" "# kitty.custom.conf -- local overrides, edit freely. Not managed by nix.\n"} "$kc"
          run chmod u+w "$kc"
        fi
      '';
    };
}
