name: Nix flake checks

on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    name: Build Nix targets
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v9

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4

      - name: Setup Magic-Nix-Cache
        uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: Check home-manager configurations
        run: |
          nix flake check --show-trace
